// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiSMS.Interface;

#nullable disable

namespace MultiSMS.Interface.Migrations.LocalDb
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20250226113753_Junction-Table")]
    partial class JunctionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiSmsSender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId");

                    b.ToTable("ApiSmsSenders");
                });

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiSmsSenderUser", b =>
                {
                    b.Property<int>("ApiSmsSenderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApiSmsSenderId", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ApiSmsSenderUsers");
                });

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiSmsSender", b =>
                {
                    b.HasOne("MultiSMS.Interface.Entities.ApiToken", "ApiToken")
                        .WithMany()
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiToken");
                });

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiSmsSenderUser", b =>
                {
                    b.HasOne("MultiSMS.Interface.Entities.ApiSmsSender", "ApiSmsSender")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("ApiSmsSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiSmsSender");
                });

            modelBuilder.Entity("MultiSMS.Interface.Entities.ApiSmsSender", b =>
                {
                    b.Navigation("AssignedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
